DROP TABLE IF EXISTS "devices";

CREATE TABLE "devices" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEVICE_CODE VARCHAR(50),
    DEVICE_NAME VARCHAR(100),
    MANUFACTURER VARCHAR(100),
    BRAND VARCHAR(100),
    MODEL VARCHAR(100),
    SUPPLIER VARCHAR(100),
    PRODUCTION_DATE DATE,
    SERVICE_LIFE INTEGER,
    DEPRECIATION_METHOD VARCHAR(50),
    LOCATION VARCHAR(100),
    STATUS VARCHAR(20),
    TYPE VARCHAR(50),
    IMAGE VARCHAR(500),
    TECHNICAL_PARAMS TEXT,
    SPARE_PARTS_INFO TEXT,
    CREATE_TIME DATE,
    UPDATE_TIME DATE
);